
[package]
name = "tools"
version = "0.1.0"
authors = []
# We never publish our tasks
publish = false
edition = "2018"

[dependencies]
svd2rust = { git = "https://github.com/rust-embedded/svd2rust", commit="77da805eb1afc4dcb5fd04ec992cde71b32d3832" }
rustfmt-nightly = "1.0.0"
form = "0.5.0"
